### ISSUE TITLE
onandaのサンプルソース

### ISSUE THREAD

**Issue by maxcus** [ryogrid/fx_systrade#2]
trap_repeat_trade_oanda.py を拝見したのですが
import している oanda_acount_infoはどこに定義されてますでしょうか？

前提として何かしらinstall の必要がありますでしょうか？

**Comment by ryogrid** [comment]
使用している変数(oandaのアクセスキー)を定義したoanda_account_info.pyを自分で作っておく必要があります。
自分のアカウントのキーを誤ってgithubに上げないようにするため、gitにはファイルを登録していません。
